### ISSUE TITLE
Please choose and specify a license for your code

### ISSUE THREAD

**Issue by LukeGoodsell** [uci-cbcl/HLA-bind#1]
Hi,

I just saw your intriguing paper in OUP Bioinformatics. Unfortunately, since you haven't specified a license under which the repo is distributed, it [might not be legal](https://choosealicense.com/no-license/) for me (and others) to download and use your code. [This website](https://choosealicense.com/) provides an easy way to pick a license that suits your needs. I'd really appreciate it if you could choose a license and include a notice in your readme that states which one you've chosen.

Thanks!

**Comment by ysvang** [comment]
Got it. Thank you for the tip.
